// MessageKind.js — the transcript's presentation metadata, rendered as text.
//
// Background
// ----------
// A `say_this` line the model produces during a turn is generated by the client,
// not returned by the daemon, so it reaches the widget as the core's
// `inline_note` view-event rather than as a transcript message. The event
// carries the line's kind as an ABI token — `normal` / `spoken` /
// `speech_disabled` (api-model's `MessageKind`, projected by client-ui-common's
// ffi/src/view_event.rs) — alongside the unmarked text.
//
// The core used to stringify that kind into the text itself. It no longer does:
// the token is structured so each client can render the affordance it actually
// has. The plasmoid has none — no badge, no per-bubble chrome for a note — so
// here the affordance IS the marker text, and the wording below is deliberately
// byte-identical to what the core used to emit.
//
// Factored as a pure module so it is:
//   • Unit-testable from qmltestrunner without instantiating the full ChatView
//     (which depends on Plasma QML modules unavailable in a generic test env).
//   • Shared byte-identically by both plasmoid copies of ChatView.qml (the
//     `just chatview-sync` mirror keeps the files in lockstep).
//
// Public API
// ----------
//   markerFor(kind) -> string
//       The prefix shown for a kind token; "" for `normal`, for an unknown
//       token, and for a missing one (an older core sends no `kind`).
//
//   decorate(text, kind) -> string
//       The note body to append to the transcript: markerFor(kind) + text.
//
.pragma library

// The marker prefix for a kind token. Unknown / absent tokens render nothing
// rather than the raw token: a kind this build predates must degrade to an
// ordinary note, never leak wire vocabulary into the transcript.
function markerFor(kind) {
    switch (kind) {
    case "spoken":
        return "Spoken: "
    case "speech_disabled":
        return "(speech mode disabled) "
    default:
        return ""
    }
}

// The full note body for the transcript. Note the marker is derived from the
// structured token only — the text is never inspected, so a note whose own
// prose opens with "Spoken:" is left exactly as the model wrote it.
function decorate(text, kind) {
    var body = (text === null || text === undefined) ? "" : String(text)
    return markerFor(kind) + body
}
